# Site settings
baseurl = "http://example.org/"
languageCode = "en-us"
title = "Sunstrakt"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Sunstrakt"
    subtitle = "Get something beautiful."
    author = "ABSTRAKTOR"
    description = "Hugrid - grid theme for Hugo with an expanding image preview."
    keywords = "Abstract Art, color, posters, interior design, geomtric, minimalism."

    # Body background color
    bodybgcolor = "#fafafa"

    # Preview container button text
    buttontext = ""

    # Footer text
    footertext = "Made by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/), [Hugo](http://gohugo.io) and [me](https://github.com/aerohub)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
    custom_css = ['css/custom.css']
